name: Pull Requests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run go report card on PR
      run: make score GITOPS_API_KEY=${{ secrets.GITOPS_API_KEY }} GITHUB_USER=gogitops GITHUB_TOKEN=${{secrets.GITHUB_API_TOKEN}}
    - name: Build the Docker image
      run: make docker_build
    - name: Build the ARM Docker image
      run: make docker_build GOARCH=arm